# Change these first
owner: racerxdl # Your GitHub username
repo: teske-status # Your GitHub repository name

# Add your sites here
sites:
  - name: "Let's Hack It"
    url: https://lucasteske.dev
    icon: https://lucasteske.dev/favicon.ico
  - name: "OpenSatelliteProject RocketChat"
    url: https://osp.teske.net.br
    icon: https://osp.teske.net.br/favicon.ico
  - name: "Scientist Poems"
    url: https://scientistpoems.lucasteske.dev
    icon: https://scientistpoems.lucasteske.dev/favicon.ico

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lucasteske.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Teske's Lab Status Page"
  introTitle: "Here you can check the status of all Teske's Lab Pages"
  introMessage: "" 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
assignees:
  - racerxdl
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
